namespace WoWAddonLab.Emulator.Lua;

public sealed record WowTraitNodeInfoState(
    int Id,
    int PosX,
    int PosY,
    int Flags,
    IReadOnlyList<int> EntryIds,
    IReadOnlyList<int> EntryIdsWithCommittedRanks,
    bool CanPurchaseRank,
    bool CanRefundRank,
    bool IsAvailable,
    bool IsVisible,
    bool IsDisplayError,
    int RanksPurchased,
    int RanksIncreased,
    IReadOnlyDictionary<int, int> EntryIdToRanksIncreased,
    int ActiveRank,
    int CurrentRank,
    WowTraitNodeEntryState? ActiveEntry,
    WowTraitNodeEntryState? NextEntry,
    int MaxRanks,
    int TotalMaxRanks,
    int Type,
    IReadOnlyList<WowTraitVisibleEdgeState> VisibleEdges,
    bool MeetsEdgeRequirements,
    IReadOnlyList<int> GroupIds,
    IReadOnlyList<int> ConditionIds,
    bool IsCascadeRepurchasable,
    int? CascadeRepurchaseEntryId,
    int? SubTreeId,
    bool? SubTreeActive);
