namespace WoWAddonLab.Emulator.Lua;

public sealed record WowCraftingOrderInfoState(
    ulong OrderId,
    int ItemId,
    int SpellId,
    int SkillLineAbilityId,
    byte OrderType,
    uint OrderState,
    int ExpirationTime,
    int ClaimEndTime,
    int MinimumQuality,
    ulong TipAmount,
    ulong ConsortiumCut,
    bool IsRecraft,
    bool IsFulfillable,
    uint ReagentState,
    string? CustomerGuid = null,
    string? CustomerName = null,
    string? CrafterGuid = null,
    string? CrafterName = null,
    int? NpcCustomerCreatureId = null,
    string CustomerNotes = "",
    string? OutputItemHyperlink = null,
    string? OutputItemGuid = null,
    string? RecraftItemHyperlink = null,
    int NpcCraftingOrderSetId = 0,
    int NpcTreasureId = 0,
    IReadOnlyList<WowCraftingOrderReagentState>? Reagents = null,
    IReadOnlyList<WowCraftingOrderNpcRewardState>? NpcOrderRewards = null);
