using LuaNET.Lua51;

namespace WoWAddonLab.Emulator.Lua;

internal sealed class LuaApiCatalog
{
    private readonly IReadOnlyList<ILuaApiModule> _modules;

    private LuaApiCatalog(params ILuaApiModule[] modules)
    {
        _modules = modules;
    }

    public static LuaApiCatalog Bootstrap { get; } = new(
        new WowLegacyEnumApi(),
        new WowCurveApi(),
        new WowStringUtilApi(),
        new WowDurationApi(),
        new WowDurationUtilApi()
    );

    public static LuaApiCatalog Game { get; } = new(
        new WowActionApi(),
        new WowGroupLootApi(),
        new WowUnitApi(),
        new WowClientApi(),
        new WowConsoleApi(),
        new WowGmTicketApi(),
        new WowZoneTextApi(),
        new WowTimeApi(),
        new WowConnectionApi(),
        new WowAutoCompleteApi(),
        new WowCursorApi(),
        new WowCameraApi(),
        new WowCinematicApi(),
        new WowPerformanceApi(),
        new WowPlayerInfoApi(),
        new WowVideoOptionsApi(),
        new WowLocalizationApi(),
        new WowStringApi(),
        new WowPlayerScriptApi(),
        new WowSpellConfirmationApi(),
        new WowClassApi(),
        new WowChatApi(),
        new WowChatInfoApi(),
        new WowClickBindingsApi(),
        new WowTargetApi(),
        new WowTitleApi(),
        new WowGameRulesApi(),
        new WowRestrictedActionsApi(),
        new WowPlayerMentorshipApi(),
        new WowAccountApi(),
        new WowAccountStoreApi(),
        new WowGroupApi(),
        new WowBindingApi(),
        new WowMacroApi(),
        new WowColorApi(),
        new WowDyeColorApi(),
        new WowTextureApi(),
        new WowSpecializationApi(),
        new WowClassTalentsApi(),
        new WowCVarApi(),
        new WowTotemApi(),
        new WowDateAndTimeApi(),
        new WowVoiceChatApi(),
        new WowUnitAuraApi(),
        new WowUnitAurasPrivateApi(),
        new WowInstanceApi(),
        new WowPvpApi(),
        new WowCommentatorApi(),
        new WowPartyInfoApi(),
        new WowPvpInfoApi(),
        new WowWeeklyRewardsApi(),
        new WowMythicPlusApi(),
        new WowMajorFactionsApi(),
        new WowPlayerInteractionManagerApi(),
        new WowLootJournalApi(),
        new WowLootHistoryApi(),
        new WowIncomingSummonApi(),
        new WowArtifactApi(),
        new WowEquipmentApi(),
        new WowPaperDollApi(),
        new WowShapeshiftApi(),
        new WowMinimapApi(),
        new WowReputationApi(),
        new WowNamePlateApi(),
        new WowUiWidgetManagerApi(),
        new WowHousingApi(),
        new WowHousingBasicModeApi(),
        new WowHouseEditorApi(),
        new WowHousingDecorApi(),
        new WowHousingCustomizeModeApi(),
        new WowPingApi(),
        new WowContainerApi(),
        new WowNewItemsApi(),
        new WowBankApi(),
        new WowMerchantApi(),
        new WowItemApi(),
        new WowTooltipInfoApi(),
        new WowWorldTimerApi(),
        new WowLegacyProgressionApi(),
        new WowQuestSessionApi(),
        new WowCraftingOrdersApi(),
        new WowCalendarApi(),
        new WowKioskApi(),
        new WowMountJournalApi(),
        new WowLobbyMatchmakerApi(),
        new WowTraitApi(),
        new WowItemUpgradeApi(),
        new WowTtsSettingsApi(),
        new WowSettingsUtilApi(),
        new WowSocialRestrictionsApi(),
        new WowGarrisonApi(),
        new WowCovenantsApi(),
        new WowClubFinderApi(),
        new WowCovenantCallingsApi(),
        new WowClubApi(),
        new WowBattleNetApi(),
        new WowFriendApi(),
        new WowRecentAlliesApi(),
        new WowEditModeApi(),
        new WowLfgListApi(),
        new WowXmlApi(),
        new WowWowLabsDataManagerApi(),
        new WowQuestLogApi(),
        new WowQuestInteractionApi(),
        new WowQuestOfferApi(),
        new WowQuestInfoSystemApi(),
        new WowQuestLineApi(),
        new WowVignetteApi(),
        new WowEventSchedulerApi(),
        new WowEventUtilsApi(),
        new WowMapApi(),
        new WowCatalogShopApi(),
        new WowGameUiApi(),
        new WowInputApi(),
        new WowMovementApi(),
        new WowProfessionApi(),
        new WowMapExplorationApi(),
        new WowScenarioApi(),
        new WowScenarioInfoApi(),
        new WowSeasonInfoApi(),
        new WowAddOnApi(),
        new WowStoreSecureApi(),
        new WowSocialQueueApi(),
        new WowGuildInfoApi(),
        new WowLfgInfoApi(),
        new WowAdventureJournalApi(),
        new WowStorePublicApi(),
        new WowPlayerChoiceApi(),
        new WowSummonInfoApi(),
        new WowInvasionInfoApi(),
        new WowEncounterJournalApi(),
        new WowRaidLocksApi(),
        new WowTaxiMapApi(),
        new WowFogOfWarApi(),
        new WowContributionCollectorApi(),
        new WowBarberShopApi(),
        new WowTradeInfoApi(),
        new WowItemSocketInfoApi(),
        new WowIslandsQueueApi(),
        new WowRemixArtifactUiApi(),
        new WowAreaPoiInfoApi(),
        new WowDeathInfoApi(),
        new WowDeathRecapApi(),
        new WowTaskQuestApi(),
        new WowGossipInfoApi(),
        new WowSpellTargetingApi(),
        new WowFunctionContainersApi(),
        new WowCharacterServicesPublicApi(),
        new WowSecureExecutionApi(),
        new WowFrameScriptApi(),
        new WowCombatLogApi(),
        new WowContentTrackingApi(),
        new WowCombatAudioAlertApi(),
        new WowSoundApi(),
        new WowSoundGameSystemApi(),
        new WowWidgetNamespaceApi(),
        new WowAdventureMapApi(),
        new WowAchievementApi(),
        new WowAuctionHouseApi(),
        new WowBlackMarketApi(),
        new WowTrainerApi(),
        new WowChromieTimeApi(),
        new WowStableInfoApi(),
        new WowAzeriteEmpoweredItemApi(),
        new WowAzeriteEssenceApi(),
        new WowItemInteractionApi(),
        new WowLegendaryCraftingApi(),
        new WowScrappingMachineApi(),
        new WowSoulbindsApi(),
        new WowCombatTextApi(),
        new WowNavigationApi(),
        new WowAddOnProfilerApi(),
        new WowModelInfoApi(),
        new WowSpellApi(),
        new WowSpellDiminishApi(),
        new WowCurrencyInfoApi(),
        new WowDamageMeterApi(),
        new WowPetBattlesApi(),
        new WowTradeSkillUiApi(),
        new WowGuildBankApi(),
        new WowPetJournalApi(),
        new WowPetInfoApi(),
        new WowToyBoxApi(),
        new WowCollectionsApi(),
        new WowTransmogApi(),
        new WowTransmogOutfitInfoApi(),
        new WowCharacterServicesApi(),
        new WowHousingNeighborhoodApi(),
        new WowNeighborhoodInitiativeApi(),
        new WowHousingCatalogApi(),
        new WowPerksApi(),
        new WowLegacyFeatureApi(),
        new WowLegacyPanelApi(),
        new WowEncodingUtilApi(),
        new WowMailApi(),
        new WowInspectApi(),
        new WowSplashScreenApi(),
        new WowTutorialApi(),
        new WowSurveyApi(),
        new WowTrophyApi(),
        new WowClientFeatureApi(),
        new WowTimerApi(),
        new WowBitApi()
    );

    public void RegisterAll(lua_State state)
    {
        foreach (var module in _modules)
            module.Register(state);
    }
}
